import 'package:get/get.dart';
class LocaleString extends Translations {
  @override
   Map<String, Map<String, String>> get keys => {
    'en_US': {
          "My Booking": "My Booking",
          "Payments": "Payments",
          "Rate us": "Rate us",
          "rafer": "Refer & Earn",
    },
    'hi_US': {
          "My Booking": "मेरी बुकिंग",
          "Wallet": "बटुआ",
          "Profile": "प्रोफ़ाइल",
          "Notification": "अधिसूचना",
          "Country": "देश",
          "Language": "भाषा",
          "English(US)": "अंग्रेजी",
          "Help Center": "सहायता केंद्र",
          "Invite Friends": "मित्रों को आमंत्रित करें",
          "Logout": "लॉग आउट",
          "Dark Mode": "डार्क मोड",
          "Are you sure you want to log out?":
              "क्या आप लॉग आउट करना चाहते हैं?",
          "Cancle": "कैंकल",
          "Yes, Remove": "हाँ, हटाओ",
          "Coupons": "कूपन",
          "Property Title": "संपत्ति का शीर्षक",
          "Full Name": "पूरा नाम",
          "Please enter your name": "कृपया अपना नाम दर्ज करें",
          "Book For Someone": "किसी के लिए बुक करें",
          "Your Information Details": "आपकी जानकारी का विवरण",
          "First Name": "पहला नाम",
          "Please enter your first name": "कृपया अपना पहला नाम दें",
          "Last Name": "उपनाम",
          "Please enter your last name": "कृपया अपना अंतिम नाम दर्ज करें",
          "Email": "ईमेल",
          "Please enter your email": "अपना ईमेल दर्ज करें",
          "Mobile Number": "मोबाइल नंबर",
          "Please enter your number": "कृपया अपना नंबर दर्ज करें",
          "Continue": "जारी रखना",
          "Please fill all required fields": "कृपया सभी आवश्यक फ़ील्ड भरें",
          "Book Real Estate": "बुक रियल एस्टेट",
          "Select Date": "तारीख़ चुनें",
          "Check in": "चेक इन",
          "Check out": "चेक आउट",
          "Number of Guest": "अतिथि की संख्या",
          "Note to Owner (optional)": "स्वामी के लिए नोट (वैकल्पिक)",
          "Notes": "टिप्पणियाँ",
          "Booking for someone": "किसी के लिए बुकिंग",
          "Home": "घर",
          "Search": "खोज",
          "Favorite": "पसंदीदा",
          "Account": "खाता",
          "BUY": "खरीदना",
          "Sorry, Search Data Not Found": "क्षमा करें, खोज डेटा नहीं मिला",
          "Sorry, there is no any nearby \n category or data not found":
              "क्षमा करें, आस-पास कोई \n श्रेणी नहीं है या डेटा नहीं मिला है",
          "Apply": "आवेदन करना",
          "Available coupons": "उपलब्ध कूपन",
          "Use": "उपयोग",
          "E-Receipt": "ई-रसीद",
          "Date": "तारीख",
          "Tax": "कर",
          "Coupon": "कूपन",
          "Total": "कुल",
          "Name": "नाम",
          "Phone Number": "फ़ोन नंबर",
          "Payment Title": "भुगतान शीर्षक",
          "Transaction ID": "लेन-देन आईडी",
          "Copy": "कॉपी",
          "Status": "दर्जा",
          "Paid": "चुकाया गया",
          "Review": "समीक्षा",
          "Leave a Review": "समीक्षा लिखें",
          "How was your experience": "आपका अनुभव कैसा रहा",
          "Write Your Review": "अपना आलेख लिखो",
          "Your review here...": "यहां आपकी समीक्षा...",
          "Maybe Later": "शायद बाद में",
          "Submit": "जमा करना",
          "Helps & FAQs": "सहायता और अक्सर पूछे जाने वाले प्रश्न",
          "Favorites": "पसंदीदा",
          "Sorry, Favorite List Empty": "क्षमा करें, पसंदीदा सूची खाली है",
          "Remove from Favorites?": "पसंदीदा से निकालें?",
          "Featured": "प्रदर्शित",
          "Gallary": "गैलरी",
          "Hello Welcome 👋": "नमस्कार स्वागत है 👋",
          "User": "उपयोगकर्ता",
          "See All": "सभी देखें",
          "Our Recommendation": "हमारी सिफारिश",
          "Search...": "खोज...",
          "Suggested": "सुझाव दिया",
          "Let's sign you in.": "आइए आपको साइन इन करते हैं",
          "Welcome back. You've been missed!":
              "वापसी पर स्वागत है। आपको याद किया गया है!",
          "Please enter your mobile number": "अपना मोबाइल नंबर दर्ज करें",
          "Please enter your password": "अपना पासवर्ड दर्ज करें",
          "Password": "पासवर्ड",
          "Remember me": "पहचाना की नहीं",
          "Forgot Password?": "पासवर्ड भूल गए?",
          "Login": "लॉग इन करें",
          "OR": "या",
          "Continue as a Guest": "अतिथि के रूप में जारी रखें",
          "Don't have an account?": "खाता नहीं है?",
          "Sign Up": "साइन अप करें",
          "Massage": "मालिश",
          "Active": "सक्रिय",
          "Completed": "पुरा होना।",
          "Go & Book your favorite service": "जाओ और अपनी पसंदीदा सेवा बुक करो",
          "New": "नया",
          "We'll let you know when we\nget news for you":
              "हम आपको बताएंगे कि जब हम आपके लिए समाचार प्राप्त करेंगे",
          "The Perfect choice for": "के लिए बिल्कुल सही विकल्प",
          "your future": "आपका भविष्य",
          "Login With Phone Number": "फोन नंबर से लॉगिन करें",
          "Verification Code": "सत्यापन कोड",
          "We have sent the code verification to":
              "हमने कोड सत्यापन को भेज दिया है",
          "Didn't receive code?": "कोड नहीं मिला?",
          "Resend New Code": "नया कोड पुनः भेजें",
          "Verify": "सत्यापित करना",
          "Please enter your valid OTP": "कृपया अपना वैध ओटीपी दर्ज करें",
          "Create Your New Password": "अपना नया पासवर्ड बनाएं",
          "Conform Password": "पासवर्ड अनुरूप करें",
          "Reset Password": "Reset Password",
          "Please enter your phone number to request a\npassword reset":
              "पासवर्ड रीसेट करने का\nअनुरोध करने के लिए कृपया अपना फोन नंबर दर्ज करें",
          "Request OTP": "ओटीपी का अनुरोध करें",
          "You remember your password?": "आपको अपना पासवर्ड याद है?",
          "Review Summary": "समीक्षा सारांश",
          "Remove": "निकालना",
          "Add": "जोड़ना",
          "Pay from Wallet": "वॉलेट से भुगतान करें",
          "Wallet Balance": "वॉलेट बैलेंस",
          "Available for Payment ": "भुगतान हेतु उपलब्ध है",
          "Congratulations!": "बधाई हो!",
          " v successfully\n booked. You can chack your booking\n on the menu Profile":
              "आधुनिक अपार्टमेंट सफलतापूर्वक\n बुक किया गया। आप मेन्यू प्रोफ़ाइल पर अपनी बुकिंग\n देख सकते हैं",
          "View E-Receipt": "ई-रसीद देखें",
          "Select Payment Method": "भुगतान का तरीका चुनें",
          "Add Your payment information": "अपनी भुगतान जानकारी जोड़ें",
          "What number is written on card?": "कार्ड पर कौन सा नंबर लिखा है?",
          "Number behind the card": "कार्ड के पीछे नंबर",
          "CVV": "सीवीवी",
          "MM/YY": "महीना साल",
          "Expiry Date": "समाप्ति तिथि",
          "Payment card is valid": "भुगतान कार्ड मान्य है",
          "Select Country": "बटुआ",
          "Get Started!": "शुरू हो जाओ!",
          "Create an account to continue.": "जारी रखने के लिए एक खाता बनाएँ।",
          "Email Address": "मेल पता",
          "Referral code (optional)": "रेफ़रल कोड (वैकल्पिक)",
          "By creating an account,you agree to our":
              "एक खाता बनाकर, आप हमारी सहमति देते हैं",
          "Terms and Condition": "नियम व शर्तें",
          "Please select Terms and Condition": "कृपया नियम और शर्त चुनें",
          "Already have an account?": "क्या आपके पास पहले से एक खाता मौजूद है?",
          "GoProperty": "गोप्रॉपर्टी",
          "Manage your properties with ease and \nget instant alert about responses":
              "अपनी संपत्तियों को आसानी से प्रबंधित करें और \nप्रतिक्रियाओं के बारे में तत्काल अलर्ट प्राप्त करें",
          "Listing Agent": "लिस्टिंग एजेंट",
          "Partner": "साझेदार",
          "Overview": "अवलोकन",
          "Read more": "और पढ़ें",
          "Show less": "कम दिखाएं",
          "Facillities": "सुविधाएँ",
          "Location": "जगह",
          "Price": "कीमत",
          "Book": "किताब",
          "Contacted": "व्यक्ति से संपर्क किया",
          "Enquiry Already Send!!": "जांच पहले से ही भेजें!!",
          "Inquiry": "जाँच करना",
          "Please login and send enquery": "कृपया लॉगिन करें और पूछताछ भेजें",
          "Update": "अद्यतन",
          "Add Wallet": "बटुआ जोड़ें",
          "Your current Balance": "आपका वर्तमान शेष",
          "Add Amount": "राशि जोड़ें",
          "Refer a Friend": "एक मित्र को सूचित करें",
          "Share the referral link with your friends":
              "अपने दोस्तों के साथ रेफ़रल लिंक साझा करें",
          "History": "इतिहास",
          "ADD AMOUNT": "राशि जोड़ें",
          "Please don`t press back until the transaction is complete":
              "लेन-देन पूरा होने तक कृपया वापस न दबाएं",

          "Amount": "मात्रा",
          "days": "दिन",
          "Booking Date": "बुक करने की तिथि",
          "/night": "/रात",
          "Beds": "बेड",
          "Bath": "नहाना",
          "sqft": "वर्गफुट",
          "About this space": "इस स्पेस के बारे में",
          "What this place offers": "यह स्थान क्या प्रदान करता है",
          "Allowed Max": "अनुमत मैक्स",
          "Guest": "अतिथि",
          "Not Paid": "भुगतान नहीं",
          "Friend get": "मित्र प्राप्त करें",
          "on their first complete\ntransaction": "उनके पहले पूर्ण\nलेन-देन पर",
          "You get": "आपको मिला",
          "on your wallet": "आपके बटुए पर",
          "for Each\n Friend you refer":
              "प्रत्येक\n मित्र के लिए जिसे आप संदर्भित करते हैं",
          "Earn": "कमाना",
          "Are you sure you want to delete account?":
              "क्या आप वाकई खाता हटाना चाहते हैं?",
          "Delete Account": "खाता हटा दो",
          "founds": "पाया",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
          // "Wallet": "बटुआ",
        },

        'fr_US': {
          "My Booking": "Ma réservation",
          "Wallet": "Portefeuille",
          "Profile": "Profil",
          "Notification": "Notification",
          "Country": "Pays",
          "Language": "Langue",
          "English(US)": "Anglais (États-Unis)",
          "Help Center": "Centre d'aide",
          "Invite Friends": "Inviter des amis",
          "Logout": "Se déconnecter",
          "Dark Mode": "Mode sombre",
          "Are you sure you want to log out?":
              "Êtes-vous sûr de vouloir vous déconnecter?,",
          "Cancle": "Annuler",
          "Yes, Remove": "Oui, supprimer",
          "Coupons": "Coupons",
          "Property Title": "Titre de propriété",
          "Full Name": "Nom et prénom",
          "Please enter your name": "S'il vous plaît entrez votre nom",
          "Book For Someone": "Réserver pour quelqu'un",
          "Your Information Details": "Vos informations détaillées",
          "First Name": "Prénom",
          "Please enter your first name": "Entrez votre prénom s'il vous plait",
          "Last Name": "Nom de famille",
          "Please enter your last name": "Veuillez entrer votre nom de famille",
          "Email": "E-mail",
          "Please enter your email": "Veuillez saisir votre e-mail",
          "Mobile Number": "Numéro de portable",
          "Please enter your number": "Veuillez entrer votre numéro",
          "Continue": "Continuer",
          "Please fill all required fields":
              "Veuillez remplir tous les champs obligatoires",
          "Book Real Estate": "Réserver un bien immobilier",
          "Select Date": "Sélectionner une date",
          "Check in": "Enregistrement",
          "Check out": "Vérifier",
          "Number of Guest": "Nombre d'invités",
          "Note to Owner (optional)": "Note au propriétaire (facultatif)",
          "Notes": "Remarques",
          "Booking for someone": "Réservation pour quelqu'un",
          "Home": "Maison",
          "Search": "Recherche",
          "Favorite": "Préféré",
          "Account": "Compte",
          "BUY": "ACHETER",
          "Sorry, Search Data Not Found":
              "Désolé, données de recherche introuvables",
          "Sorry, there is no any nearby \n category or data not found":
              "Désolé, il n'y a pas de catégorie \n à proximité ou de données introuvables",
          "Apply": "Appliquer",
          "Available coupons": "Coupons disponibles",
          "Use": "Utiliser",
          "E-Receipt": "Reçu électronique",
          "Date": "Date",
          "Tax": "Impôt",
          "Coupon": "Coupon",
          "Total": "Total",
          "Name": "Nom",
          "Phone Number": "Numéro de téléphone",
          "Payment Title": "Titre du paiement",
          "Transaction ID": "identifiant de transaction",
          "Copy": "Copie",
          "Status": "Statut",
          "Paid": "Payé",
          "Review": "Examen",
          "Leave a Review": "Laisser un commentaire",
          "How was your experience": "Comment était votre expérience",
          "Write Your Review": "Donnez votre avis",
          "Your review here...": "Votre avis ici...",
          "Maybe Later": "Peut-être plus tard",
          "Submit": "Soumettre",
          "Helps & FAQs": "Aides et FAQ",
          "Favorites": "Favoris",
          "Sorry, Favorite List Empty": "Désolé, la liste des favoris est vide",
          "Remove from Favorites?": "Retirer des favoris?",
          "Featured": "Mis en exergue",
          "Gallary": "Galerie",
          "Hello Welcome 👋": "Bonjour Bienvenue 👋",
          "User": "Utilisateur",
          "See All": "Voir tout",
          "Our Recommendation": "Notre recommandation",
          "Search...": "Recherche...",
          "Suggested": "Suggéré",
          "Let's sign you in.": "Nous allons vous connecter.",
          "Welcome back. You've been missed!":
              "Content de te revoir. Vous nous avez manqué !",
          "Please enter your mobile number":
              "Entrez s'il vous plaît votre numéro de téléphone",
          "Please enter your password":
              "s'il vous plait entrez votre mot de passe",
          "Password": "Mot de passe",
          "Remember me": "Souviens-toi de moi",
          "Forgot Password?": "Mot de passe oublié?",
          "Login": "Connexion",
          "OR": "OU",
          "Continue as a Guest": "Continuer en tant qu'invité",
          "Don't have an account?": "Vous n'avez pas de compte ?",
          "Sign Up": "S'inscrire",
          "Massage": "Massage",
          "Active": "Actif",
          "Completed": "Complété",
          "Go & Book your favorite service":
              "Go & Réservez votre service préféré",
          "New": "Nouveau",
          "We'll let you know when we\nget news for you":
              "Nous vous informerons lorsque nous aurons des nouvelles pour vous",
          "The Perfect choice for": "Le choix parfait pour",
          "your future": "ton futur",
          "Login With Phone Number": "Se connecter avec un numéro de téléphone",
          "Verification Code": "Le code de vérification",
          "We have sent the code verification to":
              "Nous avons envoyé la vérification du code à",
          "Didn't receive code?": "Vous n'avez pas reçu de code ?",
          "Resend New Code": "Renvoyer le nouveau code",
          "Verify": "Vérifier",
          "Please enter your valid OTP": "Veuillez entrer votre OTP valide",
          "Create Your New Password": "Créez votre nouveau mot de passe",
          "Conform Password": "Conformez le mot de passe",
          "Reset Password": "réinitialiser le mot de passe",
          "Please enter your phone number to request a\npassword reset":
              "Veuillez saisir votre numéro de téléphone pour demander une\nréinitialisation du mot de passe",
          "Request OTP": "Demander OTP",
          "You remember your password?":
              "Vous vous souvenez de votre mot de passe ?",
          "Review Summary": "Résumé des commentaires",
          "Remove": "Retirer",
          "Add": "Ajouter",
          "Pay from Wallet": "Payer depuis Wallet",
          "Wallet Balance": "Solde du portefeuille",
          "Available for Payment ": "Disponible pour paiement",
          "Congratulations!": "Toutes nos félicitations!",
          "Successfully\n booked. You can chack your booking\n on the menu Profile":
              "Appartement moderne réservé avec succès. Vous pouvez vérifier votre réservation\n dans le menu Profil",
          "View E-Receipt": "Afficher le reçu électronique",
          "Select Payment Method": "Sélectionnez le mode de paiement",
          "Add Your payment information":
              "Ajoutez vos informations de paiement",
          "What number is written on card?":
              "Quel numéro est inscrit sur la carte ?",
          "Number behind the card": "Numéro derrière la carte",
          "CVV": "CVV",
          "MM/YY": "MM/AA",
          "Expiry Date": "Date expiration",
          "Payment card is valid": "La carte de paiement est valide",
          "Select Country": "Choisissez le pays",
          "Get Started!": "Commencer!",
          "Create an account to continue.": "Créez un compte pour continuer.",
          "Email Address": "Adresse e-mail",
          "Referral code (optional)": "Code de parrainage (facultatif)",
          "By creating an account,you agree to our":
              "En créant un compte, vous acceptez nos",
          "Terms and Condition": "Termes et conditions",
          "Please select Terms and Condition":
              "Veuillez sélectionner les termes et conditions",
          "Already have an account?": "Vous avez déjà un compte?",
          "GoProperty": "AllerPropriété",
          "Manage your properties with ease and \nget instant alert about responses":
              "Gérez facilement vos propriétés et \nobtenez une alerte instantanée sur les réponses",
          "Listing Agent": "Agent inscripteur",
          "Partner": "Partenaire",
          "Overview": "Aperçu",
          "Read more": "En savoir plus",
          "Show less": "Montrer moins",
          "Facillities": "Installations",
          "Location": "Emplacement",
          "Price": "Prix",
          "Book": "Livre",
          "Contacted": "Contacté",
          "Enquiry Already Send!!": "Demande déjà envoyée !!",
          "Inquiry": "Demande",
          "Please login and send enquery":
              "Veuillez vous connecter et envoyer la demande",
          "Update": "Mise à jour",
          "Add Wallet": "Ajouter un portefeuille",
          "Your current Balance": "Votre solde actuel",
          "Add Amount": "Ajouter un montant",
          "Refer a Friend": "Référez un ami",
          "Share the referral link with your friends":
              "Partagez le lien de parrainage avec vos amis",
          "History": "Histoire",
          "ADD AMOUNT": "AJOUTER LE MONTANT",
          "Please don`t press back until the transaction is complete":
              "Veuillez ne pas appuyer sur retour jusqu'à ce que la transaction soit terminée",
          "Amount": "Montant",
          "days": "jours",
          "Booking Date": "Date de réservation",
          "/night": "/nuit",
          "Beds": "Des lits",
          "Bath": "Bain",
          "sqft": "pieds carrés",
          "About this space": "A propos de cet espace",
          "What this place offers": "Ce que cet endroit offre",
          "Allowed Max": "Max autorisé",
          "Guest": "Invité",
          "Not Paid": "Impayé",
          "Friend get": "Ami obtenir",
          "on their first complete\ntransaction":
              "lors de leur première\ntransaction complète",
          "You get": "Vous obtenez",
          "on your wallet": "sur votre portefeuille",
          "for Each\n Friend you refer": "pour chaque\n ami que vous parrainez",
          "Earn": "Gagner",
          "Are you sure you want to delete account?":
              "Voulez-vous vraiment supprimer le compte ?",
          "Delete Account": "Supprimer le compte",
          "founds": "fonde",
          "Tukki":"Tukki",
          "Manage your property with ease and get instant alert about responses":"Manage your property with ease and get instant alert about responses",
        },
   };
}